### ISSUE TITLE
Bolivian Flag incorrect

### ISSUE THREAD

**Issue by danielaparra** [apilayer/restcountries#109]
The Bolivian flag is missing the emblem with the national bird. It's not the Bolivian flag without the emblem.

**Comment by Danny-Engelman** [comment]
**+1**

Missing emblem is a  major mistake

![image](https://user-images.githubusercontent.com/3382713/60680977-b96cbf80-9e8d-11e9-976d-527583c9b4e1.png)

**Comment by mledoze** [comment]
:wave: Hello, this issue has been fixed on https://github.com/mledoze/countries by pull request mledoze/countries#342.
Diff: https://github.com/mledoze/countries/pull/342/files?short_path=50ab598#diff-50ab598d13300c5805c62774b68b6739

**Comment by ePascalC** [comment]
Correct flags uploaded
