### ISSUE TITLE
Mexico is located in Northern America

### ISSUE THREAD

**Issue by ChocoC** [apilayer/restcountries#111]
Getting information about countries through the Dyno bot (which redirects to restcountries.eu), I got that Mexico was located in Central America. This is wrong no matter which continental model one is following. Mexico is always North America or Northern America. Please, correct it. It not only important for issues like the "new NAFTA" (NORTH AMERICAN Free Trade Agreement, between Canada, U.S. and Mexico), but also for Mexico's and real Central America's identity. Thank you.

**Comment by Raykud** [comment]
just to add or to be more clear, the subregion returned is: `subregion: "Central America",`when it should be something like `subregion: "North America"`.

**Comment by ePascalC** [comment]
As per UN region/subregion, Mexico is in Central America. Please note that this categorization is not the same as Continents.
https://unstats.un.org/unsd/methodology/m49/#geo-regions
