### ISSUE TITLE
Malay language is missing a a country code for `iso639_1`

### ISSUE THREAD

**Issue by spina-a-d** [apilayer/restcountries#112]
The language Malaysian has no `iso639_1` code when it should be `ms`.
You can find it here:
https://restcountries.eu/rest/v2/name/malaysia
The correct one is here:
https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=ms

**Comment by Amn3s1a2018** [comment]
Hey, it seems a bit more complicated ... 
I'm not sure about your suggestion (what the hack is a macrolanguage). But there are various iso639-2 codes, im rly not an expert about this... so based on info here:

https://iso639-3.sil.org/code_tables/639/data/all?title=&field_iso639_cd_st_mmbrshp_639_1_tid=All&name_3=malay&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=All&items_per_page=200
With the 639-1 code ms there are two -2 codes, i would go with the following:
```
{
  iso639_1: "ms",
  iso639_2: "msa", // T code
  name: "Malay",
  nativ: "بهاس ملايو‎" // wikipedia
}
```
The current code `zsm` is part of 639-3 standard. The -3 and -5 codes seems not covered by the application so its definitly wrong. Almost the same i found at [Brunei](https://restcountries.eu/rest/v2/name/brunei) and [Singapore]https://restcountries.eu/rest/v2/name/singapore):

```
{
  iso639_1: "ms",
  iso639_2: "msa", // T code
  name: "Malay",
  nativ: "bahasa Melayu"
}
```
so i think we are on right trace with this.

For make the changes more doable, the JSON format should be converted to JSON5.

Any help from @apilayer
@fourcube maybe pls pls.
