### ISSUE TITLE
Countries Aruba(AW) and Curaçao (CW) show wrong language

### ISSUE THREAD

**Issue by papiando** [apilayer/restcountries#118]
It shows {"iso639_1":"pa","iso639_2":"pan","name":"(Eastern) Punjabi","nativeName":"ਪੰਜਾਬੀ"}. It should actually be , but it should be {"iso639_2":"pap","name":"Papiamento","nativeName":"Papiamentu"}. Either change it to this, or remove completely, as Punjabi is not spoken anywhere in the caribbean. It could be added to Bonaire (BQ) as well.

**Comment by ePascalC** [comment]
Fixed. Thanks.
