### ISSUE TITLE
Chad borders array missing Sudan

### ISSUE THREAD

**Issue by DaveSimmons1234** [apilayer/restcountries#120]
Hi there,

https://restcountries.eu/rest/v2/alpha/tcd

The borders for Chad (TCD) is missing Sudan (SDN) - could this be added please?

**Comment by mledoze** [comment]
Agreed, the list of borders contains SSN which is the code for South Sudan but should contains SDN instead which is the code for Sudan.

https://en.wikipedia.org/wiki/Chad

**Comment by DaveSimmons1234** [comment]
I ended up copying the file locally and make the corrections myself. There are a few border issues.

**Comment by mledoze** [comment]
Do you mind giving the issues that you noticed?

**Comment by DaveSimmons1234** [comment]
I'm sorry I can't quite remember them. Mostly borders inconsistencies in Africa then issues mentioned in github issues - i.e. Mexico subregion etc. I also processed the file to remove any data that was extraneous to my needs.
