### ISSUE TITLE
No Chinese labels for countries

### ISSUE THREAD

**Issue by meteorra** [apilayer/restcountries#131]
When retrieving the list of countries with the following endpoint https://restcountries.eu/rest/v2/all,
in the response I get countries with translations for several languages - fr, de, ja etc. Is there a possibility to get Chinese translation in the list?

**Comment by MikhailVolkov350504** [comment]
I faced the same issue. Could you please add Chinese support?

**Comment by avarapayeva** [comment]
We've prepared json with Chinese values for you. Could you please add them to the library?
It's a blocker for us to proceed with your solution.

Thank you in advance.
[Countries Chinese.zip](https://github.com/apilayer/restcountries/files/3320528/Countries.Chinese.zip)

**Comment by Pezhvak** [comment]
> We've prepared json with Chinese values for you. Could you please add them to the library?
> It's a blocker for us to proceed with your solution.
> 
> Thank you in advance.
> [Countries Chinese.zip](https://github.com/apilayer/restcountries/files/3320528/Countries.Chinese.zip)

you need to have two fields for each translation. common and official. the service that you are talking about is using [mledoze/countries](https://github.com/mledoze/countries. if you want to add this translation, you should submit your data to that repository. (i don't know if they are pulling updates from the repo as of now or not, you should contact restcountries.eu to make sure)

**Comment by Pezhvak** [comment]
> We've prepared json with Chinese values for you. Could you please add them to the library?
> It's a blocker for us to proceed with your solution.
> 
> Thank you in advance.
> [Countries Chinese.zip](https://github.com/apilayer/restcountries/files/3320528/Countries.Chinese.zip)

you need to have two fields for each translation. common and official. the service that you are talking about is using [mledoze/countries](https://github.com/mledoze/countries). if you want to add this translation, you should submit your data to that repository. (i don't know if they are pulling updates from the repo as of now or not, you should contact restcountries.eu to make sure)

**Comment by MikhailVolkov350504** [comment]
@Pezhvak Thank you fo the reply!
After looking through [mledoze/countries](https://github.com/mledoze/countries) repo I noticed they already have Chinese language support (_"zho"_ translation code) and even some others.

Could you please update source files to add Chines support?

**Comment by svdHero** [comment]
Any update on this? This is a crucial feature that is stopping us from using this library. China is an important market and if we cannot display country names in Chinese this great library is useless for us.

**Comment by amatosg** [comment]
@svdHero & @MikhailVolkov350504  you can use [this](https://restcountries.com) project to get Chinese translations, [like](https://restcountries.com/v3/name/peru?fields=name,translations) in this example. Repository is [here](https://gitlab.com/amatos/rest-countries).

**Comment by ePascalC** [comment]
Added with https://github.com/apilayer/restcountries/pull/256
