### ISSUE TITLE
‼️ Peru flag is missing the detail crest

### ISSUE THREAD

**Issue by Danny-Engelman** [apilayer/restcountries#134]
https://restcountries.eu/data/per.svg

![image](https://user-images.githubusercontent.com/3382713/60681196-a7d7e780-9e8e-11e9-8d02-3ab2413a1e44.png)

## https://commons.wikimedia.org/wiki/File:Flag_of_Peru_(state).svg

![image](https://user-images.githubusercontent.com/3382713/60681140-65160f80-9e8e-11e9-8d55-3703d8ae10f3.png)

**Comment by mledoze** [comment]
:wave: Hello, this issue has been fixed on https://github.com/mledoze/countries by pull request https://github.com/mledoze/countries/pull/341.

**Comment by ePascalC** [comment]
Implemented
