### ISSUE TITLE
Different flag aspect ratios

### ISSUE THREAD

**Issue by Leon99** [apilayer/restcountries#140]
Svgs of different flags here have different sizes and aspect ratios, which makes it hard to visualise them in a list.
I noticed the initial issue re. adding flags had http://flag-icon-css.lip.is mentioned as a potential source of the flags, which have all the flags in the same ratio (4:3 or 1:1). I wonder why it wasn't eventually used - @fayder?

**Comment by ePascalC** [comment]
@Leon99 https://flagpedia.net/australia/download/api has lots of different sizes and a great CDN network if you look for other sizes.
