### ISSUE TITLE
Update Mexico's subregion to "Northern America"

### ISSUE THREAD

**Issue by aoiotoko** [apilayer/restcountries#150]
Mexico has an erroneous subregion of "Central America".

**Comment by Amn3s1a2018** [comment]
It seems to me current version `"subregion": "Central America"` is fine, according to [UNSD](https://unstats.un.org/unsd/methodology/m49/#geo-regions)

**Comment by amatosg** [comment]
@aoiotoko you're correct. Mexico is in North America. I have a cloned project [here](https://gitlab.com/amatos/rest-countries). You can check Mexico [here](https://restcountries.com/v2/alpha/codes=mx).

**Comment by ePascalC** [comment]
As per UN region/subregion, Mexico is in Central America. Please note that this categorization is not the same as Continents.
https://unstats.un.org/unsd/methodology/m49/#geo-regions
