### ISSUE TITLE
Kosovo translations are null

### ISSUE THREAD

**Issue by erikyo** [apilayer/restcountries#152]
Some Kosovo translations are null (de, fr, ja, it, nl) 

https://restcountries.eu/rest/v2/name/kosovo

{"de":null,"es":"Kosovo","fr":null,"ja":null,"it":null,"br":"Kosovo","pt":"Kosovo","nl":null,"hr":"Kosovo","fa":"کوزوو"}

have to be:
{"de":"Kosovo","es":"Kosovo","fr":"Kosovo","ja":"コソボ","it":"Kosovo","br":"Kosovo","pt":"Kosovo","nl":"Kosovo","hr":"Kosovo","fa":"کوزوو"}

**Comment by ePascalC** [comment]
Was fixed in an earlier commit
