### ISSUE TITLE
Why is there no continent key?

### ISSUE THREAD

**Issue by RichMatthews** [apilayer/restcountries#171]
i'm confused why there is a lack of `continent` key for each country?

I see there is a `region` and `subregion` but for example Mexico and Honduras are in North America but this doesn't appear in their respective responses. why is this? and would you be able to put this in?

**Comment by amatosg** [comment]
well, take region as Continent, although you're right: it should be Continent instead of Region and Region instead of Subregion.
BTW: Mexico is in North America, but Honduras is in Central America.

**Comment by mikerockett** [comment]
Just bumped into this as well – continents need to be added separately. Regions are not the same thing.

**Comment by amatosg** [comment]
So, I decided to address this issue as it's actually the correct way to name those fields. As this project doesn't show much activity, I have another version. You can find the corrected version [here](https://restcountries.com/v2/alpha/codes=mx?fields=name,continent,region).

**Comment by mikerockett** [comment]
Thanks for putting that up. 🙂 I figured nothing might be updated on the repo, so landed up going with https://datahub.io/core/country-codes, which contains all the data I need.

**Comment by mikerockett** [comment]
I just had a look at your commit for this, and noticed that it isn't entirely correct. Will open an issues on your repo. 🙂
