### ISSUE TITLE
Updating Data

### ISSUE THREAD

**Issue by MonilBhavsar** [apilayer/restcountries#174]
The data provided by API seems to be old. The population of India returned by API is 1295210000 while the current population of India is 1378712489.

**Comment by amatosg** [comment]
I fixed it in my project, you can see it [here](https://restcountries.com/v2/name/india?fields=population;name;capital) (it's a clone of this, but updated 😉 )

**Comment by MonilBhavsar** [comment]
Please Push that changes in the main repo, so that everyone is benefited by the updated data :)

**Comment by amatosg** [comment]
the reason for me to clone this project is that there wasn't any activity for the last 14 months. The API for this project is https:/restcountries.eu and I have created [https:/restcountries.com](https:/restcountries.com) the functionality is the same and it's available to everyone :)

For India, [the example I showed you](https://restcountries.com/v2/name/india?fields=population;name;capital) returns this:

```json
[
  {
    "name": "British Indian Ocean Territory",
    "capital": "Diego Garcia",
    "population": 3000
  },
  {
    "name": "India",
    "capital": "New Delhi",
    "population": 1378712489
  }
]
```

**Comment by MonilBhavsar** [comment]
How can I get the data by its alpha code from your api?
For Eg: https://restcountries.eu/rest/v2/alpha?codes=in

**Comment by amatosg** [comment]
As I have a slightly different implementation, in mine goes like this: https://restcountries.com/v2/alpha/codes=in

**Comment by ePascalC** [comment]
#255 merged with 2020 data
