### ISSUE TITLE
TRY currency has a symbol

### ISSUE THREAD

**Issue by moltar** [apilayer/restcountries#175]
https://en.wikipedia.org/wiki/Turkish_lira

`TRY` currency is missing it's symbol in the API.

**Comment by amatosg** [comment]
I added the currency in my project that works almost exactly like this one. You can see it [here](https://restcountries.com/v2/name/turkey?fields=currencies). My project is [here](https://gitlab.com/amatos/rest-countries/)

**Comment by amatosg** [comment]
I added the Turkish Lira in my project [here](https://gitlab.com/amatos/rest-countries). You can see the result [here](https://restcountries.com/v2/name/turkey?fields=name;currencies;languages)

**Comment by ePascalC** [comment]
Fixed, thanks.
