### ISSUE TITLE
Incomplete currency/language list for Antarctica

### ISSUE THREAD

**Issue by dbize** [apilayer/restcountries#177]
There is an incomplete currency list for "Antarctica". 

It should include Chilean Peso CLP and Spanish.

Below a portion of the response with available currencies and languages.

```
{
  "name" : "Antarctica",
  "alpha2Code" : "AQ",
  "callingCodes" : [ "672" ],
  "region" : "Polar",
  "timezones" : [ "UTC-03:00", "UTC+03:00", "UTC+05:00", "UTC+06:00", "UTC+07:00", "UTC+08:00", "UTC+10:00", "UTC+12:00" ],
  "nativeName" : "Antarctica",
  "currencies" : [ {
    "code" : "AUD",
    "name" : "Australian dollar",
    "symbol" : "$"
  }, {
    "code" : "GBP",
    "name" : "British pound",
    "symbol" : "£"
  } ],
  "languages" : [ {
    "iso639_1" : "en",
    "iso639_2" : "eng",
    "name" : "English",
    "nativeName" : "English"
  }, {
    "iso639_1" : "ru",
    "iso639_2" : "rus",
    "name" : "Russian",
    "nativeName" : "Русский"
  } ]
}
```

**Comment by amatosg** [comment]
After I took my time to research, there is no official currency for Antarctica. Although each base can accept its local currency, Antactica itself doesn't have an official one.

**Comment by dbize** [comment]
I opened this issue because the Chilean base accepts its local currency, Chilean Peso (CLP).

**Comment by amatosg** [comment]
that's what I meant with _Although each base can accept its local currency_. Each base accept its currency, but **officially** it doesn't have a currency. I mean no disrespect here, really.

**Comment by dbize** [comment]
That's ok but is unclear what that means for this issue.

**Comment by amatosg** [comment]
it means that Antarctica shouldn't have any currency, it should be an empty array
