### ISSUE TITLE
obsolete entry in restcountries

### ISSUE THREAD

**Issue by DAP-GitHub** [apilayer/restcountries#178]
Macedonia is now "North Macedonia" (and not Former....) since February 2019. The translations in different language should take this in account.
How frequently is the rest file updated ?

**Comment by amatosg** [comment]
you can edit the files and the project owner would have to approve your changes

**Comment by DAP-GitHub** [comment]
I don't think it is a good idea to do "manual" corrections to very complex files depending on external "official" sources. I suppose the country file is made and updated programatically by using these sources.

**Comment by amatosg** [comment]
@DAP-GitHub I'm forking this project to make the changes requested and also implement new features. Please take a look at http://restcountries.com/v2/name/eesti right now I'm working on getting the SSL certificate, but I'll have it soon.

**Comment by amatosg** [comment]
If you have any other ideas, please let me know [here](https://gitlab.com/amatos/rest-countries)
