### ISSUE TITLE
Too many Time Zones for France

### ISSUE THREAD

**Issue by irinael** [apilayer/restcountries#179]
- Actual data received  :
![image](https://user-images.githubusercontent.com/52750054/83772457-b07b0400-a683-11ea-9bbb-cf1edf340d1b.png)

- Should be : UTC+2

**Comment by amatosg** [comment]
could it be because other territories France has? Even if that's true, +2 is missing

**Comment by irinael** [comment]
Right, of course ! In the spirit of full exhaustiveness, UTC+10 might also be added (one of the Antarctic French Lands)

https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands

**Comment by amatosg** [comment]
I added the +2 and +10 to France :)

**Comment by amatosg** [comment]
@irinael I cloned the project and I'm working on adding SSL security, in the meantime, you can get the modified result here: http://restcountries.com/v2/name/france

**Comment by irinael** [comment]
Great, thank you !

**Comment by amatosg** [comment]
If you have any other ideas, please let me know [here](https://gitlab.com/amatos/rest-countries)

**Comment by ePascalC** [comment]
UTC+02 is summer time, only 'normal' times should be mentioned.
