### ISSUE TITLE
Faroe Islands are not a part of the EU

### ISSUE THREAD

**Issue by mewa** [apilayer/restcountries#184]
`https://restcountries.eu/rest/v2/regionalbloc/eu` lists Faroe Islands as part of the EU. Wikipedia says the following and it seems to be right in this case:
> As explicitly asserted by both treaties of the European Union, the Faroe Islands are not part of the European Union.

**Comment by amatosg** [comment]
@mewa as this project doesn't show much activity, I decided to clone this project. You can find the fixed version [here](https://restcountries.com/v2/name/faro?fields=name,regionalBlocs). If you have any other issues, please add an issue [here](https://gitlab.com/amatos/rest-countries)
