### ISSUE TITLE
Typo in currency of American Samoa

### ISSUE THREAD

**Issue by flikkr** [apilayer/restcountries#185]
The currency is the US dollar, but it is written as "United State dollar" instead of "United State**s** dollar" like other countries.

**Comment by amatosg** [comment]
As this repository is not as active as I would love to, I've cloned it. I corrected the typo [here](https://restcountries.com/v2/name/samoa).

**Comment by flikkr** [comment]
Thanks, is there any rate limiting on your clone?

**Comment by amatosg** [comment]
None that I know of :)

**Comment by ePascalC** [comment]
Fixed, thanks.
