### ISSUE TITLE
issue in Morocco's data

### ISSUE THREAD

**Issue by abderrahimbouali** [apilayer/restcountries#186]
please check the `translations `object: you have written مراكش as a value for `fa` but مراكش which is Marrakech in English it's a city in Morocco

```
translations: {
br: "Marrocos"
de: "Marokko"
es: "Marruecos"
fa: "مراکش"
fr: "Maroc"
hr: "Maroko"
it: "Marocco"
ja: "モロッコ"
nl: "Marokko"
pt: "Marrocos" 
}
```

**Comment by amatosg** [comment]
what would be the correct value?

**Comment by abderrahimbouali** [comment]
it should be المغرب

**Comment by amatosg** [comment]
@abderrahimbouali as this project doesn't show much activity, I decided to clone this project. You can find the fixed version [here](https://restcountries.com/v2/name/morocco?fields=name,translations). If you have any other issues, please add an issue [here](https://gitlab.com/amatos/rest-countries)
