### ISSUE TITLE
Missing Central Europe

### ISSUE THREAD

**Issue by boson-higgs** [apilayer/restcountries#187]
Please look at https://en.wikipedia.org/wiki/Central_Europe and edit countries which belong to Central Europe.
For instance you have at Czech Republic - Eastern Europe and at Austria - Western Europe -> that's geographically impossible.

**Comment by boson-higgs** [comment]
@amatosg are you going to fix it in your fork on GitLab or do I have to make new issue in your GitLab's repo?

**Comment by boson-higgs** [comment]
@amatosg are you going to fix it in your clone on GitLab or do I have to make new issue in your GitLab's repo?

**Comment by amatosg** [comment]
you are correct, Austria is not in Western Europe. I will be fixing this tonight. Regarding issues, I would appreciate issues in my repo :) but I'm watching this repo _just in case_

**Comment by amatosg** [comment]
Fixed! 😃  🇨🇿 
https://restcountries.com/v2/name/Czech

**Comment by ePascalC** [comment]
This API is following the UN divisions, see https://en.wikipedia.org/wiki/Subregion#Europe
So it seems correct for Austria and Czech Republic like it is.
