### ISSUE TITLE
Malaysia missing language iso639_1 code

### ISSUE THREAD

**Issue by haluunn** [apilayer/restcountries#188]
The code should be 'ms', according to https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by amatosg** [comment]
could you be more specific? There is no Malay translation

**Comment by haluunn** [comment]
When running this in python
requests.get(url='https://restcountries.eu/rest/v2/name/Malaysia?fullText=true')

I got the result:
[{'name': 'Malaysia', 'topLevelDomain': ['.my'], 'alpha2Code': 'MY', 'alpha3Code': 'MYS', 'callingCodes': ['60'], 'capital': 'Kuala Lumpur', 'altSpellings': ['MY'], 'region': 'Asia', 'subregion': 'South-Eastern Asia', 'population': 31405416, 'latlng': [2.5, 112.5], 'demonym': 'Malaysian', 'area': 330803.0, 'gini': 46.2, 'timezones': ['UTC+08:00'], 'borders': ['BRN', 'IDN', 'THA'], 'nativeName': 'Malaysia', 'numericCode': '458', 'currencies': [{'code': 'MYR', 'name': 'Malaysian ringgit', 'symbol': 'RM'}], 'languages': [{'iso639_1': None, 'iso639_2': 'zsm', 'name': 'Malaysian', 'nativeName': 'بهاس مليسيا'}], 'translations': {'de': 'Malaysia', 'es': 'Malasia', 'fr': 'Malaisie', 'ja': 'マレーシア', 'it': 'Malesia', 'br': 'Malásia', 'pt': 'Malásia', 'nl': 'Maleisië', 'hr': 'Malezija', 'fa': 'مالزی'}, 'flag': 'https://restcountries.eu/data/mys.svg', 'regionalBlocs': [{'acronym': 'ASEAN', 'name': 'Association of Southeast Asian Nations', 'otherAcronyms': [], 'otherNames': []}], 'cioc': 'MAS'}]

In languages:
'languages': [{'iso639_1': None, 'iso639_2': 'zsm', 'name': 'Malaysian', 'nativeName': 'بهاس مليسيا'}]

the code 'iso639_1' of Malaysian should be 'ms', not None

**Comment by amatosg** [comment]
this has been fixed [here](https://restcountries.com/v2/name/Malaysia?fullText=true). Is not from this project, but another project based on this one.

**Comment by ePascalC** [comment]
Updated, thanks.
