### ISSUE TITLE
Pakistan official language is Urdu.

### ISSUE THREAD

**Issue by syedmahmad** [apilayer/restcountries#189]
Pakistan official language is urdu but in JSON response, priority language is english
![image](https://user-images.githubusercontent.com/29013374/88475257-a53baa80-cf47-11ea-9672-26d2e89c077c.png)
Urdu should be in top priority like if you check indian languages you can see Hindi is in top priority.
![image](https://user-images.githubusercontent.com/29013374/88475282-de741a80-cf47-11ea-8f5d-ecc89a3851c9.png)

**Comment by amatosg** [comment]
As this project doesn't show much activity, I've addressed this issue in [my](https://gitlab.com/amatos/rest-countries) project. You can find the corrected version [here](https://restcountries.com/v2/alpha/codes=pk?fields=name,continent,languages).

**Comment by syedmahmad** [comment]
Thanks @amatosg appreciate it.
