### ISSUE TITLE
Suriname has no border with France

### ISSUE THREAD

**Issue by MarcoMadera** [apilayer/restcountries#191]
[![](https://i.imgur.com/HltE11N.png)](https://i.imgur.com/HltE11N.png)

**Comment by amatosg** [comment]
I fixed this in my own project. You can check the fixed version [here](https://restcountries.com/v2/name/suriname?fields=name,borders). Cheers

**Comment by amatosg** [comment]
if you find any other issue, you can submit it [here](https://gitlab.com/amatos/rest-countries/-/issues).

**Comment by ePascalC** [comment]
Suriname has a border with French Guiana, an oversees department of France, so it DOES have a border with France.

**Comment by amatosg** [comment]
ohhh, you're right! I reverted the changes [here](https://restcountries.com/v2/name/suriname?fields=name,borders).

**Comment by MarcoMadera** [comment]
Ok, in that case brazil should have a border with France too? [Brazil-France border](https://en.wikipedia.org/wiki/Brazil%E2%80%93France_border)

Brazil borders:
![brazil-borders](https://user-images.githubusercontent.com/17222523/89960851-ae926b80-dc05-11ea-87be-b3e6944b35e6.png)

**Comment by amatosg** [comment]
I think it should. This applies the same as with Suriname, right?

**Comment by ePascalC** [comment]
Fixed in https://github.com/apilayer/restcountries/pull/268
