### ISSUE TITLE
The data for currencies are mixed up in many places

### ISSUE THREAD

**Issue by ashishbeck** [apilayer/restcountries#193]
There are multiple places where the currencies section has more than one entry which doesn't make sense and it makes data interpretation difficult.

![image](https://user-images.githubusercontent.com/20200594/90310806-bfe3bc80-df12-11ea-89e7-ab731f8b4f32.png)

**Comment by amatos-aeropost** [comment]
Well, there are countries in which you can trade in different currencies. For Tuvalu, for instance, the Wikipedia states that they have both currencies as official.

**Comment by amatosg** [comment]
Well, there are countries in which you can trade in different currencies. For Tuvalu, for instance, the Wikipedia states that they have both currencies as official.
