### ISSUE TITLE
Are we down? (error 521)

### ISSUE THREAD

**Issue by renato-bohler** [apilayer/restcountries#195]
I'm receiving this error when trying to fetch anything from `restcountries.eu`

![image](https://user-images.githubusercontent.com/25781956/90523962-df156080-e143-11ea-9fba-57ef7e68416d.png)

**Comment by amatosg** [comment]
I have a similar project to this. You can try it on [here](https://restcountries.com/v2/alpha/codes=pe) (note that mine is _.com_ and not _.eu_)

**Comment by j-hit** [comment]
@fayder any ideas why it is down?

**Comment by najamulabideen** [comment]
It's down for the last 2 hours now. Any idea what's going on guys?

**Comment by amatosg** [comment]
You can check [this](https://gitlab.com/amatos/rest-countries) actually active project and call the APIs according to the docs.

**Comment by j-hit** [comment]
I tagged [apilayer](https://apilayer.com/) in a tweet to see if they are aware of this.

Please retweet. Pinned to top of https://twitter.com/dj_jhit

**Comment by fayder** [comment]
Please contact @apilayer Unfortunately I can't do anything as I don't own this project anymore.

**Comment by j-hit** [comment]
Thanks @fayder for your response. Reached out to them via twitter. Do you know the best way to get in touch with them?

**Comment by descaloni-cc** [comment]
Any update from apilayer or status update at all?

**Comment by SaracenoNicolas** [comment]
I tried to reach @apilayer but their work hour starts in 4 hours so probably can't expect much until then

**Comment by renato-bohler** [comment]
> You can check [this](https://gitlab.com/amatos/rest-countries) actually active project and call the APIs according to the docs.

@amatosg I was trying to use this as an alternative to `restcountries.eu`, but I'm being blocked by CORS. I've submitted this [issue](https://gitlab.com/amatos/rest-countries/-/issues/11).

**Comment by amatosg** [comment]
> > You can check [this](https://gitlab.com/amatos/rest-countries) actually active project and call the APIs according to the docs.
> 
> @amatosg I was trying to use this as an alternative to `restcountries.eu`, but I'm being blocked by CORS. I've submitted this [issue](https://gitlab.com/amatos/rest-countries/-/issues/11).

Thanks! talk to you over there.

**Comment by amrfaissal** [comment]
> I have a similar project to this. You can try it on [here](https://restcountries.com/v2/alpha/codes=pe) (note that mine is _.com_ and not _.eu_)

@amatosg Do you have documentation of your version of the API? Thanks!

**Comment by renato-bohler** [comment]
Its timing out now, instead of returning 521 error.

**Comment by SaracenoNicolas** [comment]
it is working for me now

**Comment by amatosg** [comment]
> > I have a similar project to this. You can try it on [here](https://restcountries.com/v2/alpha/codes=pe) (note that mine is _.com_ and not _.eu_)
> 
> @amatosg Do you have documentation of your version of the API? Thanks!

is almost the same (for the sake of simplicity) https://gitlab.com/amatos/rest-countries
