### ISSUE TITLE
How does one deploy this project?

### ISSUE THREAD

**Issue by fais3000** [apilayer/restcountries#197]
This is an amazing resource, however https://restcountries.eu sometimes go down. Is there a way to self host this? Any instructions?

**Comment by amatosg** [comment]
well, you have [https://restcountries.com/](https://restcountries.com/v2/name/austria) :) (documentation [here](https://gitlab.com/amatos/rest-countries))

**Comment by fais3000** [comment]
> https://restcountries.com/

@amatosg Thanks, we actually moved to https://restcountries.com because https://restcountries.eu went down in august. But https://restcountries.com was down for about 6 hours today too, that's why looking to self host. Do you have docs on self deploying?

**Comment by amatosg** [comment]
yeah, I realized there as an issue with the SSL proxy while posting this, otherwise it would have gone unnoticed (by me, of course lol). I'm going to post all the code in that repo. There are some credentials in the code, so I cannot post it right now, but I'll make some time in a few days with all the instructions :)

**Comment by fais3000** [comment]
@amatosg Sounds good. Happy to contribute, i'm also figuring out how to convert this to dockerized version for easy self hosting.

**Comment by amatosg** [comment]
I have it dockerized, I'll make those images available very soon

**Comment by FaizanZahid** [comment]
@amatosg we are facing the exact same issue,  would love to have this self hosted. cant wait to see the instructions , guide and images.

**Comment by fais3000** [comment]
If any one stumbles on this issue. I used one of the forks of this repo and added deployment instructions for others. https://github.com/fais3000/restcountries

**Comment by FaizanZahid** [comment]
awesome work @fais3000 in contributing on open source
