### ISSUE TITLE
restcountries.com is going down frequently 

### ISSUE THREAD

**Issue by FaizanZahid** [apilayer/restcountries#198]
hi,

I have noticed this a number times that https://restcountries.com goes down with either 502 error or 404. Right now if I go on that url I am getting 404 error.
![image](https://user-images.githubusercontent.com/9073066/92461318-0e5a4300-f1c1-11ea-966a-48aeae199c6d.png)

Can you guys please fix this and keep it 200 ok response ? Also is there any other way for us to use this API internally or locally without relying on CDN, as this CDN is not reliable. 

I have also tried using https://restcountries.eu but many end points of this are different and it is causing lot of conflicts on our project. 

please fix this or provide us a better fall back solution asap.

**Comment by ePascalC** [comment]
Hi, this repository is all about restcountries.eu and has nothing to see with the forked .com version.

**Comment by FaizanZahid** [comment]
@ePascalC ok , can you please share with me the repo URL of the https://restcountries.com/ >?

**Comment by amatosg** [comment]
If you want to run it locally, you can use the docker image:
`docker pull registry.gitlab.com/amatos/rest-countries:latest`
and run it with
`docker run -d -p 8080:8080 registry.gitlab.com/amatos/rest-countries:latest`
