### ISSUE TITLE
Populations are so outdated.

### ISSUE THREAD

**Issue by Arsh1a** [apilayer/restcountries#200]
Are there any plans for updating the information?

**Comment by amatosg** [comment]
please update the discrepancies to help the community

**Comment by Arsh1a** [comment]
> please update the discrepancies to help the community

I would gladly do but need a guide on how to that.

**Comment by amatosg** [comment]
If you just list the correct values I would gladly update it

**Comment by Arsh1a** [comment]
@amatosg I've forked the repo and I'm working on it. Will request-pull as soon as it gets ready!

**Comment by ePascalC** [comment]
#255 merged with 2020 data
