### ISSUE TITLE
Brazil should border Suriname

### ISSUE THREAD

**Issue by lennertVanSever** [apilayer/restcountries#202]
If you check the bordering countries of Suriname https://restcountries.eu/rest/v2/name/suriname, you will see that France is a bordering country. However, for Brazil, this isn't the case https://restcountries.eu/rest/v2/name/brazil while it should

**Comment by amatosg** [comment]
but Suriname is being shown in the list of borders for Brazil

**Comment by lennertVanSever** [comment]
What I mean is that Brazil should border France. Since it's bordering French Guiana which is a French department

**Comment by amatosg** [comment]
I think the logic is that Guyana borders France as it's part of France, but it doesn't particularly means that Brazil, by extension, borders France

**Comment by lennertVanSever** [comment]
<img width="742" alt="Screenshot 2020-10-04 at 02 34 20" src="https://user-images.githubusercontent.com/23064517/95004341-33887880-05ea-11eb-8043-a89c40eb61a0.png">
This is a screenshot from google maps, as you can see both Suriname and Brazil border "French Guyana" which is France. In the API call for Suriname I get the following bordering countries which include France: 
```
"borders": [
"BRA",
"GUF",
"FRA",
"GUY"
],
```
While for Brazil I don't get France:
```
"borders": [
"ARG",
"BOL",
"COL",
"GUF",
"GUY",
"PRY",
"PER",
"SUR",
"URY",
"VEN"
],
```
```

**Comment by amatosg** [comment]
I was confusing French Guyana with Suriname :) my bad. I think the error is considering France bordering Suriname, but I'm not sure. Is there any references to corroborate this information?

**Comment by zocky** [comment]
French Guyana is France the same way as Paris is France.

**Comment by amatosg** [comment]
it's easier and less prone to errors to link a reference rather to just state "it does". I took the exhausting job of entering a single query into the wikipedia and found [this](https://en.wikipedia.org/wiki/Borders_of_Brazil), which makes @lennertVanSever's poing.

**Comment by amatosg** [comment]
So, I fixed this issue in a [cloned project](https://restcountries.com/) as this doesn't have much activity. You can find the source [here](https://gitlab.com/amatos/rest-countries) and check the fix [here](https://restcountries.com/v2/name/brazil).
