### ISSUE TITLE
Wrong 3 Digit ISO Code for Netherlands Antilles

### ISSUE THREAD

**Issue by Flow09AT** [apilayer/restcountries#203]
Correct ISO code is **ANT** not ANG
See https://www.iso.org/obp/ui/#iso:code:3166:AN

**Comment by amatosg** [comment]
what's the full URL you're using to get the Netherlands Antilles' info?

**Comment by ePascalC** [comment]
You were probably looking at the ANG currency acronym and not at the code of the 'country'
