### ISSUE TITLE
Wrong currency symbol for Georgian Lari

### ISSUE THREAD

**Issue by Esul** [apilayer/restcountries#205]
Georgian Lari has its own symbol "₾", not just the letter "ლ".

**Comment by amatosg** [comment]
In this case, the issue would be that the field `symbol` may only have one value. It would be necessary to add another currency with the same name and different symbol, which doesn't make any sense. The wikipedia only lists the ლ as the official currency (although the wikipedia page for Georgian Lari lists both currencies).

**Comment by Esul** [comment]
In 2014 the Lari sign was officially changed to '₾'.
This date is also mentioned in wikipedia.
sources:
https://www.nbg.gov.ge/index.php?m=630
https://www.wikiwand.com/en/Georgian_lari#/Lari

**Comment by amatosg** [comment]
> the issue would be that the field symbol may only have one value

and this
