### ISSUE TITLE
UK (GB) is not EU anymore !

### ISSUE THREAD

**Issue by SupportKraatje** [apilayer/restcountries#209]
API still outputs it as an EU country.

**Comment by SupportKraatje** [comment]
Will this be fixed ?

**Comment by SupportKraatje** [comment]
Is this API dead !?

GB, GBR ........

Regional Blocs
Acronym	EU
Name	European Union

Not fixed, will move to another API. This one is outdated.

**Comment by amatosg** [comment]
You're right. This API is outdated, that's why I cloned this project. You can find it [here](https://gitlab.com/amatos/rest-countries). The fixed version for UK is [here](https://restcountries.com/v2/name/britain). I try to update the API within hours of filing an issue :)

**Comment by ePascalC** [comment]
Fixed, thanks.
