### ISSUE TITLE
Problem of Alphabet Order

### ISSUE THREAD

**Issue by nadfri** [apilayer/restcountries#211]
Hello,
 When i get list of all countries, some countries dont respect the alphabet order, like Virgin Islands, United States Minor, Cote d'Ivoir, Korea, Qatar.

Can you fix it?

**Comment by notjasonknott** [comment]
Hey just bumping this issue up. It's still a problem.

![image](https://user-images.githubusercontent.com/28274424/128032095-1172ddeb-4f6b-4359-a215-01f88eddb5f1.png)

Could you look into fixing this?

**Comment by ePascalC** [comment]
Hi, the list is ordered by codes like cca3 or other. You need to order in the list in your own programming language based on the fields you want to order.
