### ISSUE TITLE
India border country with afghanistan

### ISSUE THREAD

**Issue by khanhmas** [apilayer/restcountries#216]
In the api reponse of the India country, there is a mistake on the borders array: 
1) the alpha3code of afghanistan (AFG) is inside the array. Though as far as i can tell,  Afghanistan is not a neighbor country with India
2) Nepal should be a neighbor country with China

**Comment by arladmin** [comment]
https://en.wikipedia.org/wiki/Borders_of_India#Land_borders_of_India

**Comment by khanhmas** [comment]
Thank for your information

But in the other hand, it's werid that India is not a neighbor country with Afghanistan.
