### ISSUE TITLE
Mauritania New Flag

### ISSUE THREAD

**Issue by miarkt** [apilayer/restcountries#217]
Mauritania has recently changed its flag. 

You can check it out here : [https://fr.wikipedia.org/wiki/Mauritanie#/media/Fichier:Flag_of_Mauritania.svg](url)

**Comment by amatosg** [comment]
Mauritania's flag has been updated in [this](https://gitlab.com/amatos/rest-countries/) project (a clone that I made to update the project more frequently). You can see the file [here](https://restcountries.com/data/mrt.svg). For more info, see [here](https://restcountries.com/).

**Comment by ePascalC** [comment]
Fixed.
