### ISSUE TITLE
Wrong native name for Luxembourg

### ISSUE THREAD

**Issue by LegendPhoenix66** [apilayer/restcountries#221]
The native name for Luxembourg isn't Luxembourg. That would be the English or french name. in Luxemburgish its "Lëtzebuerg"

**Comment by amatosg** [comment]
This [issue](https://gitlab.com/amatos/rest-countries/-/issues/23) has been closed in [this](https://gitlab.com/amatos/rest-countries/) project. You can check the result [here](https://restcountries.com/v2/name/luxe).
