### ISSUE TITLE
The capital of Ukraine is Kyiv not Kiev. 

### ISSUE THREAD

**Issue by OlehTovkaniuk** [apilayer/restcountries#222]
Kiev is the old USSR transliteration. Modern transliteration is Kyiv which is transliteration of ukrainian pronunciation while Kiev is transliteration of russian pronunciation. All the modern naming uses ukrainian transliteration since independence of Ukraine after USSR fall. You can check it on Wikipedia or Google Maps. https://en.wikipedia.org/wiki/Kyiv

**Comment by amatosg** [comment]
[Issue](https://gitlab.com/amatos/rest-countries/-/issues/21) has been solved in [this](https://gitlab.com/amatos/rest-countries/) project. You can see the result [here](https://restcountries.com/v2/name/ukraine)

**Comment by ePascalC** [comment]
Modified. Thanks.
