### ISSUE TITLE
missing .cioc

### ISSUE THREAD

**Issue by russo97** [apilayer/restcountries#223]
Some countries like Anguilla, Antarctica and Bouvet Island do not have the `cioc` property configured correctly

here `cioc` should be filled with `ATA`

![image](https://user-images.githubusercontent.com/10843387/110916611-0b840a80-832a-11eb-8756-f59abff03586.png)

here `cioc` is filled properly

![image](https://user-images.githubusercontent.com/10843387/110916920-5aca3b00-832a-11eb-83fa-d37309aea83c.png)

**Comment by ePascalC** [comment]
Not all countries have an IOC code, so it's normal that some are empty: https://en.wikipedia.org/wiki/List_of_IOC_country_codes
