### ISSUE TITLE
Norway missing a language

### ISSUE THREAD

**Issue by petmil123** [apilayer/restcountries#225]
Northern Sami is an official language in Norway

**Comment by amatosg** [comment]
According to Wikipedia:
_Sámi is an official language alongside Norwegian **in the "administrative area for Sámi language"**, that includes eight municipalities in the northern half of Norway, namely Kautokeino, Karasjok, Gáivuotna – Kåfjord – Kaivuono, Nesseby, Porsanger, Tana, Tysfjord, Lavangen and Snåsa_

It's not an official language per se, instead is an official language for certain regions. I don't see it could be considered to be an official language for the whole country.
