### ISSUE TITLE
Vietnam is called Viet Nam

### ISSUE THREAD

**Issue by DevBaddy** [apilayer/restcountries#230]
It shouldn't be spaced out.

**Comment by amatosg** [comment]
According to the Wikipedia, it's a single word and not two 😟 
https://en.wikipedia.org/wiki/Vietnam

**Comment by DevBaddy** [comment]
Yeah, but shouldn't it still be named Vietnam?

**Comment by amatosg** [comment]
oh! sorry, I misunderstood you. I see it as a single word [here](https://restcountries.com/v2/name/vietnam). Is not this project, but a cloned made by me as the updates here are not as frequent as desirable. Check it out: https://restcountries.com/

**Comment by DevBaddy** [comment]
Weird, I recently built a website that shows you all the countries that are in the world and for some reason, Vietnam's country name is spelt as Viet Nam. Sorry for the confusion.

**Comment by ePascalC** [comment]
Vietnam updated, thanks.
