### ISSUE TITLE
Any constraints/quotas for corporate use?

### ISSUE THREAD

**Issue by artkonr** [apilayer/restcountries#232]
Hey, a question rather than an issue: are there any constraints in terms of using the API for corporate systems? Any quotas applied?

**Comment by amatosg** [comment]
as this project is not being updated as often as desired, I created a clone [here ](https://gitlab.com/amatos/rest-countries)where I update based on issues here. There is no constrains nor quotas: https://restcountries.com/

**Comment by artkonr** [comment]
Gotcha, thanks.
