### ISSUE TITLE
United States Minor Outlying Islands Dial code

### ISSUE THREAD

**Issue by AkramiPro** [apilayer/restcountries#234]
the dial code for **United States Minor Outlying Islands** is +246 . please add this to api .

**Comment by amatosg** [comment]
this [issue](https://gitlab.com/amatos/rest-countries/-/issues/25) has been fixed in [this](https://gitlab.com/amatos/rest-countries) project. You can see the change [here](https://restcountries.com/v2/name/ritish%20Indian%20Ocean%20Territory).

**Comment by AkramiPro** [comment]
thank you 🌹
