### ISSUE TITLE
Change name capital of Ukraine

### ISSUE THREAD

**Issue by F1reMonster** [apilayer/restcountries#235]
You have wrong name capital of Ukraine, in your API use Kiev ithis transcription name used only russian who live in Russia, in all world used valid name Kyiv
https://en.wikipedia.org/wiki/Kyiv#cite_note-12

#KyivNotKiev

**Comment by amatosg** [comment]
Please remember that this project hasn't seen many activity in the last months. I have cloned this project [here](https://gitlab.com/amatos/rest-countries). Please read the docs as, right now, there are 2 versions, each with different country structure. You can compare [V2](https://restcountries.com/v2/capital/Kyiv) and [V3](https://restcountries.com/v3/capital/Kyiv).

**Comment by ePascalC** [comment]
Fixed. Thanks.
