### ISSUE TITLE
There should be Nepal in border countries of China

### ISSUE THREAD

**Issue by binamracode** [apilayer/restcountries#237]
If you try to fetch border countries of Nepal then there is China and India. If you fetch borders of India then there is Nepal too but when you fetch borders of China then there is not Nepal which there must be.

**Comment by amatosg** [comment]
I added [this issue](https://gitlab.com/amatos/rest-countries/-/issues/27) to another [project](https://gitlab.com/amatos/rest-countries/). You can see the change in version 2 [here](https://restcountries.com/v2/name/china?fields=name,borders) and version 3 [here](https://restcountries.com/v3/name/china?fields=name,borders).
