### ISSUE TITLE
API is timing out on website

### ISSUE THREAD

**Issue by gear4s** [apilayer/restcountries#238]

**Comment by gear4s** [comment]
@amatosg your fork does not allow issues. https://restcountries.com/v2/regionalbloc/au has an internal server error

**Comment by amatosg** [comment]
It does: https://gitlab.com/amatos/rest-countries/-/issues

I will move it to github just for ease of use. I will take a look at what's happening today :)

**Comment by ianbunn** [comment]
Hey @amatosg , was this issue resolved? I did notice that in Incognito/Private mode, it takes ~10 seconds to fetch countries.

**Comment by amatosg** [comment]
@ianbunn it takes 515ms on incognito mode to load all countries, try hitting F12 and click on the _Network_ tab to check how long it takes

@gear4s you're correct, the throws a 500 when calling that url, I'll take a look at that

**Comment by ianbunn** [comment]
Gotcha, just re-ran a test and it loaded in 2ms. Thank you for looking, @amatosg !

**Comment by amatosg** [comment]
@gear4s bug fixed in my repo. You can retry now
