### ISSUE TITLE
time out API

### ISSUE THREAD

**Issue by fricek** [apilayer/restcountries#239]
hello,
here is the code:
url = f'https://restcountries.eu/rest/v2/name/{self.country}'
            response = requests.get(url=url)

and it give me:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/name/FRANCE (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000024ED3C90080>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by amatosg** [comment]
It might be temporary as I tried and it works. You can also try [this](https://gitlab.com/amatos/rest-countries) repository which is more up-to-date. Here is my [V2](https://restcountries.com/v2/name/france) and [V3](https://restcountries.com/v3/name/france) for France.
