### ISSUE TITLE
ISO-639-1 for Malaysia

### ISSUE THREAD

**Issue by K2ouMais** [apilayer/restcountries#241]
Hello everyone,

Wikipedia says ISO-639-1 (Language) for Malaysia is "ms".

https://de.wikipedia.org/wiki/Liste_der_ISO-639-1-Codes

Could you please extend your data, so that iso639_1 is "ms" and you still could leave iso639_2 as "zsm".

Thank you for the awesome API.

Greets from Germany
Joao Alves

**Comment by amatosg** [comment]
Hi @K2ouMais!

I have a clone of this project, you can see that Malaysia with the corrected information in a similar version as this project [here (V2)](https://restcountries.com/v2/name/malaysia) and a richer version [here (V3)](https://restcountries.com/v3/name/malaysia). If you have ideas, you can check the project [here](https://gitlab.com/amatos/rest-countries).

**Comment by K2ouMais** [comment]
Hi @amatosg,

I just saw this is implemented already on v2.

Sorry for this Issue and thanks for implementing it.

**Comment by amatosg** [comment]
@K2ouMais please bare in mind that the implementation is **not** done in **THIS** project.
