### ISSUE TITLE
API with empty parameters

### ISSUE THREAD

**Issue by fish-404** [apilayer/restcountries#242]
I find if I pass name parameter in empty, the API will return HTTP 404. 
Example: https://restcountries.eu/rest/v2/name/

Do you have some plans to enhancement this ?
Take an example, if I left the parameter empty, you can return a full list or empty list instead of HTTP404.

**Comment by amatosg** [comment]
you should use https://restcountries.eu/rest/v2/all

**Comment by fish-404** [comment]
> you should use https://restcountries.eu/rest/v2/all

Thank you . I know this API. Just suggust handle the wrong parameters for the API instead of return HTTP 404.

**Comment by amatosg** [comment]
it's an API, so the consumer should know exactly what endpoint it's being called. Handling placeholders doesn't make sense
