### ISSUE TITLE
Change the capital of Sri Lanka

### ISSUE THREAD

**Issue by vidarshanadithya** [apilayer/restcountries#243]
Capital of Sri Lanka is **Sri Jayawardenepura Kotte**, not Colombo as per the API.

**Comment by amatosg** [comment]
I have a project almost identical to this one [here](https://gitlab.com/amatos/rest-countries) where I update often. I've corrected Sri Lanka and it's available in 2 versions: [V2](https://restcountries.com/v2/name/sri?fields=name,capital) and [V3](https://restcountries.com/v3/name/sri?fields=name,capital) :wink:

**Comment by vidarshanadithya** [comment]
Sorted
