### ISSUE TITLE
Missing Spanish Translations

### ISSUE THREAD

**Issue by Joseph-WGD** [apilayer/restcountries#244]
Hey team, 

We're currently using this API to call a list of countries with Spanish translations, however we've found these countries are appearing blank on our Spanish dropdowns.

![S9HnutlUi1](https://user-images.githubusercontent.com/87853798/126759146-df2237fe-a4be-4a7e-935e-cf735c2b74c6.gif)

Any help / support would be really appreciated!

**Comment by amatosg** [comment]
what's the endpoint you're using?

**Comment by ePascalC** [comment]
Fixed in v2
