### ISSUE TITLE
/all response begins with a array [ array and not { object

### ISSUE THREAD

**Issue by zaidzak9** [apilayer/restcountries#246]
Why does the api response for https://restcountries.eu/rest/v2/all does not begin with object?
<img width="66" alt="Screen Shot 2021-08-09 at 2 06 09 PM" src="https://user-images.githubusercontent.com/11702972/128665713-78cbe61c-bc27-4c14-a5b2-490f60549168.png">

**Comment by amatosg** [comment]
because is an array of countries
