### ISSUE TITLE
Swaziland Country Name

### ISSUE THREAD

**Issue by MrSimh** [apilayer/restcountries#249]
This is not Swaziland any more, its "Eswatini" the offical name of this country.

**Comment by amatosg** [comment]
you can find an updated version [here ](https://restcountries.com/v3/name/Eswatini):)

**Comment by MrSimh** [comment]
oh ok, I have to use the v3 then, Thank you !

**Comment by amatosg** [comment]
please bear in mind that the provided URL is not from this project, but from another one cloned by me to keep the data up to date as this project is not being updated for a while now :)

**Comment by od3n** [comment]
Thanks @amatosg for the fork and update. Just notice the previous URL is down today

**Comment by amatosg** [comment]
what do you mean? I see V2 and V3 working :(

**Comment by od3n** [comment]
> what do you mean? I see V2 and V3 working :(

sorry, I mean restcountries.eu domain, not restcountries.com

**Comment by amatosg** [comment]
yes, it looks like they haven't renewed the SSL certificate :(
