### ISSUE TITLE
Endpoint down?

### ISSUE THREAD

**Issue by od3n** [apilayer/restcountries#250]

**Comment by od3n** [comment]
Just found a fork for this with the new URL https://gitlab.com/amatos/rest-countries

**Comment by amatosg** [comment]
indeed, that's my fork of this project while also adding V3 with more/better information :)

**Comment by od3n** [comment]
Can I confirm for the field separator you're using a comma instead of semicolon?

**Comment by amatosg** [comment]
Yes, I use comma, otherwise I get a security error, sorry about that :(
