### ISSUE TITLE
Invalid certificate for restcountries.eu

### ISSUE THREAD

**Issue by meta72** [apilayer/restcountries#251]
The SSL certificate for restcountries.eu is issued for shortener.secureserver.net making requests fail. Please update your certificate.

**Comment by mcknight89** [comment]
The same issue, if I ignore the SSL, I get a Cloudflare error so my guess is the service is just down.

**Comment by wollanup** [comment]
it may help :  
```
$ openssl version
> OpenSSL 1.1.0l  10 Sep 2019
$ curl "https://restcountries.eu/rest/v2/all"
> curl: (51) SSL: no alternative certificate subject name matches target host name 'restcountries.eu'
```

With another server:

```
$ openssl version
> OpenSSL 1.1.1j  16 Feb 2021
$  curl "https://restcountries.eu/rest/v2/all"
> [{...}] JSON OK
```

**Comment by wollanup** [comment]
Also checked https://www.ssllabs.com/ssltest/analyze.html?d=restcountries.eu
Result seems bad with message 
```
 This server's certificate is not trusted. 
```

**Comment by amatosg** [comment]
you can use https://restcountries.com/ instead :) (it's a clone)

**Comment by ePascalC** [comment]
Message from apilayer support: We no longer support restcountries.eu; however, we do offer a free tier of a similar API on countrylayer.com. See https://countrylayer.com/documentation/
