### ISSUE TITLE
Hard to reach the api today ?

### ISSUE THREAD

**Issue by MrSimh** [apilayer/restcountries#252]
Hello,

I run the api with this url for my little app : https://restcountries.eu/rest/v2/all?fields=name;population;capital;flag;region;alpha2Code

But today i have a lot of 502,503 and 504 error, 
I am redirected here : http://countrylayer.com/rest/v2/all?fields=name;population;capital;flag;region;alpha2Code

Is anyone have the same ?

Thx

**Comment by egpotter** [comment]
There are more people complaining here https://github.com/apilayer/restcountries/issues/251. We also face the same

**Comment by amatosg** [comment]
you can use https://restcountries.com instead :) it's a clone of this project that is updated more regularly

**Comment by heychazza** [comment]
> you can use https://restcountries.com instead :) it's a clone of this project that is updated more often

Is yours open sourced?

**Comment by amatosg** [comment]
yes, I keep the original license and it's available for free :)

**Comment by Vitaljok** [comment]
> you can use https://restcountries.com instead :) it's a clone of this project that is updated more often

@amatosg, just to keep it honest for your potential new audience, you should mention that `https://restcountries.eu/rest/v2/all` and `https://restcountries.com/v2/all` are not compatible and have different field names.

So the one who wants to migrate to new API have also to modify his code, not just URL.

**Comment by amatosg** [comment]
I never said to "just change the URL", I pointed to the site with the documentation to use the API. If the docs are not clear, please let me know and I will make the amendments.

**Comment by heychazza** [comment]
> > you can use https://restcountries.com instead :) it's a clone of this project that is updated more often
> 
> @amatosg, just to keep it honest for your potential new audience, you should mention that `https://restcountries.eu/rest/v2/all` and `https://restcountries.com/v2/all` are not compatible and have different field names.
> 
> So the one who wants to migrate to new API have also to modify his code, not just URL.

Yeah, I realised that… I ended up forking the original url, and using the dist countries.json file in my app

**Comment by amatosg** [comment]
If you just need the json file, I get it from [here](https://github.com/mledoze/countries/blob/master/countries.json) :)

**Comment by heychazza** [comment]
> If you just need the json file, I get it from [here](https://github.com/mledoze/countries/blob/master/countries.json) :)

I’m currently using https://github.com/octanna/restcountries/blob/master/src/main/resources/countriesV2.json as it’s the exact data structure that the restcountries.eu was using.

No other api including yours contains population, and the JSON Object Structure is completely different.

**Comment by heychazza** [comment]
> I have a V2 with almost the same structure (I added a png file for the flag) as this project which also includes population:
> 
> https://restcountries.com/v2/name/Eswatini

Is it possible to have the same structure as the .eu API on your domain, but with the ability to see all countries? And PNG for flag is awesome.

**Comment by amatosg** [comment]
yeap :) almost all the functionallity available here is also available in V2 (Although I think I made the mistake of changing the URL structure)

https://restcountries.com/v2/all

**Comment by heychazza** [comment]
> yeap :) almost all the functionallity available here is also available in V2 (Although I think I made the mistake of changing the URL structure)
> 
> https://restcountries.com/v2/all

Oh awesome, I’ll try this in my app soon then instead and see if there are any issues.

**Comment by heychazza** [comment]
> yeap :) almost all the functionallity available here is also available in V2 (Although I think I made the mistake of changing the URL structure)
> 
> https://restcountries.com/v2/all

Seems subregions is the only thing missing

**Comment by heychazza** [comment]
> yeap :) almost all the functionallity available here is also available in V2 (Although I think I made the mistake of changing the URL structure)
> 
> https://restcountries.com/v2/all

Hey buddy, most of this seems perfect, only issue I see is;
- `subregion` is now `region`.
- `region` is now `continent`.

These are perfectly fine, but mainly for others to consider, only issue I see is that some things don't have a `region` key, could these be present but just null?

**Comment by amatosg** [comment]
I've created an issue [here](https://gitlab.com/amatos/rest-countries/-/issues/38) to keep track of what you mention.

I just went through the file and found only a couple of cases in which `region` was not set but was present as empty. Could you tell me which country does not have the `region` field?
thanks!

**Comment by dhernandezmartinez** [comment]
@amatosg Hi there, I test your v3 solution and I found some issues in some calling codes, for example Mexico, its calling code is 52 but the API returns 484, insted I tested your v2 and I believe the returning information is more trusthy, takes for telling us abut your solution, hope the project continue and keep increasing.

**Comment by amatosg** [comment]
@dhernandezmartinez  I'm sorry, but I just checked and V3 doesn't have calling code. It has a composite code called "idd" and it is actually 52 :/

**Comment by MrSimh** [comment]
hello

unfortunatly v2 and v3 are not compatible
even flags links are unreachable, so its unfortunate (i have saved the result and put the json in local but flags are off)

And if i take and recode for the v3, i will have to recode again for the v4 ?
I just need a json, up to date, and compatible to work with my little app.
If possible, without creat mine in local with all flags and names. and [fields i need]

have a good day

**Comment by heychazza** [comment]
> hello
> 
> unfortunatly v2 and v3 are not compatible
> v2 flags links are unreachable too
> 
> And if i take and recode for the v3, i will have to recode again for the v4 ?
> I just need a json, up to date, and compatible to work with my little app.
> If possible, without creat mine in local with all flags and names. and [fields i need] to bypass the issue
> 
> have a good day

Yeah, I am finding his API is all over the place, best bet is to get the JSON file from the existing repo and reference that for your application.

**Comment by amatosg** [comment]
> unfortunatly v2 and v3 are not compatible

Well, they're obviously not compatible, hence the version number in order to avoid braking implementations.


> v2 flags links are unreachable too

They are reachable


> And if i take and recode for the v3, i will have to recode again for the v4 ?

Yes. That will apply to every API you consume.


> I just need a json, up to date, and compatible to work with my little app.

You can download the json file to your project and consume it


> I am finding his API is all over the place

Sorry about that, I will try to make it better. If you have any specifics, I would love to hear them

**Comment by MrSimh** [comment]
yes i will find a way
for flags its ok i found https://restcountries.com/data/afg.svg is ok,i had https://restcountries.eu/data/afg.svg 
thx

**Comment by amatosg** [comment]
@heychazza Hi Charlie, what do you mean with *is all over the place*?

**Comment by ePascalC** [comment]
Message from apilayer support: We no longer support restcountries.eu; however, we do offer a free tier of a similar API on countrylayer.com. See https://countrylayer.com/documentation/
