### ISSUE TITLE
You API/Website is down

### ISSUE THREAD

**Issue by snaerth** [apilayer/restcountries#288]
Hi and thank you for your API.
I was using the API for a homework assignment for my students, but the API is down.
Could you possible fix your server?

Anyways thank you for your work

**Comment by amatosg** [comment]
It seems that this API is no longer free. You can go to their website and create a token (I think). You could use restcountries.com though, is free and available

**Comment by snaerth** [comment]
hmmm do you not get a 503 Service Unavailable?

**Comment by amatosg** [comment]
this is NOT the repository for that website, please use https://gitlab.com/restcountries/restcountries/

**Comment by snaerth** [comment]
Great thank you!
