### ISSUE TITLE
server down 

### ISSUE THREAD

**Issue by mgm793** [apilayer/restcountries#289]
<img width="895" alt="Screenshot 2023-03-17 at 12 36 38" src="https://user-images.githubusercontent.com/11296854/225894063-b3e656e6-ec70-4989-af00-1dd15b08cb38.png">

**Comment by MoussaRiad** [comment]
The same problem with me, is there any alternatives?

**Comment by amatosg** [comment]
This is not the repository. Please read...

**Comment by bob-lee** [comment]
Was using v3.1 api, seems down with OPTION call getting `503 Service Unavailable` status. Hope it's a temporary issue.

**Comment by amatosg** [comment]
This is not the repository. Please read...
