### ISSUE TITLE
SSL expired

### ISSUE THREAD

**Issue by AlexandreShunpo** [apilayer/restcountries#296]
restcountries.com SSL has expired

<img width="1284" alt="Screenshot 2023-12-12 at 15 21 40" src="https://github.com/apilayer/restcountries/assets/122541970/1fd9cd18-7b74-468a-bf89-f3958e25faf9">

**Comment by amatosg** [comment]
wrong repository...

**Comment by AlexandreShunpo** [comment]
Sorry
