### ISSUE TITLE
Incorrect time zone for Portugal 

### ISSUE THREAD

**Issue by JoaoLeiria** [apilayer/restcountries#70]
Hello, 

I was using your API (great work, btw) and I noticed the timezones for Portugal are incorrect.
They are **UTC-01:00** and UTC, and should be **UTC+01:00** and UTC .(https://www.timeanddate.com/time/zone/portugal/lisbon)

Best regards,
João

**Comment by fayder** [comment]
Thanks @JoaoLeiria I will take a look
