### ISSUE TITLE
Dockerization (a naive idea)

### ISSUE THREAD

**Issue by masciugo** [apilayer/restcountries#79]
first of all thank you all for this amazing public service.

As it seem hard, at least for this year, to reach the whole budget for maintenance, even if I am aware that the best solution is as it is, I just wonder whether is possible to protect this project providing it differently. I mean, in few fords, cutting the hosting costs (switching to a less performing live service) and offering a dockerized version which can be locally scaled up.

thanks again!

**Comment by RibeiroAna** [comment]
+1
