### ISSUE TITLE
Does not exist

### ISSUE THREAD

**Issue by serobalino** [apilayer/restcountries#82]
Scotland and England do not exist in the api please help with that.

Thank you

**Comment by tomgk** [comment]
Scotland and England are not countries of their own but belong to the United Kingdom

**Comment by serobalino** [comment]
https://en.wikipedia.org/wiki/Scotland
Wikipedia Calls country
:S 
thank u

**Comment by tomgk** [comment]
Wikipedia says:

>Scotland is a country that is part of the United Kingdom

It may be called a country but they are not independent, that's why I wrote `not countries of their own`. I probably could have worded it better but that's what I meant.

restcountries.eu is only about sovereign countries, not parts of sovereign countries.

**Comment by jongon** [comment]
I wanted to use this rest api for soccer application and I need countries like England, Scotland or Wales. Are you no planning to add them?

**Comment by tomgk** [comment]
In soccer the parts of United Kingdom are treated special because it originated from there. However, this is a general country database, not one specifically for soccer.
