### ISSUE TITLE
request return 403 Forbidden

### ISSUE THREAD

**Issue by JpabloR** [apilayer/restcountries#83]
Hi,

 i have a problem with your api. Today your API started return to me 403 Forbidden when i call it from java, do you know what could be the problem, my code haven´t changed.

Please help me.

Thanks!

**Comment by artusvranken** [comment]
A few minutes ago the website was down, but the service was still available. Maybe just some connection problems with the server host.

**Comment by knirirr** [comment]
I've noticed the same thing calling it from Python:

```
url = 'https://restcountries.eu/rest/v1/all'
urlresponse = urllib2.urlopen(url, timeout=5)
```

This is still happening at the moment.

**Comment by artusvranken** [comment]
Same for me, I can use it again
