### ISSUE TITLE
CORS enabled ?

### ISSUE THREAD

**Issue by mrtplnkr** [apilayer/restcountries#96]
Hello is your services not CORS enabled ?
Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response

**Comment by AlexandreBonfim** [comment]
Did you find a solution? I was receiving the country names last week and now is complain about CORS.

**Comment by TheAifam5** [comment]
I have the same problem too.

**Comment by abhi78439** [comment]
Same issue with me too

**Comment by martatenes** [comment]
Same issue here. Any solution?

**Comment by TheAifam5** [comment]
Yea, prefetch data in API then send back to frontend.

**Comment by tonivj5** [comment]
CORS are OK, verify what headers are you sending https://github.com/apilayer/restcountries/issues/73#issuecomment-342815331
